/**
 * @component RootLayout
 * @filepath /app/layout.tsx
 * @description This component serves as the root layout for the application, providing global styles and metadata
 */

// Imports - scripts (node)
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

// Imports - scripts (local)
import '@/app/globals.css';

// Settings
const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

// Component(s)
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// Render default
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
		</html>
	);
}
